### ISSUE TITLE
Dereference $ref's except schema ones

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/parser#15]
Create a utility function to resolve all the `$ref`s in the AsyncAPI document, except the ones that are schemas.

Currently, schemas are present at:

* Topic Item Parameters
* Message payload and headers.
* `components.schemas`

### References

* https://github.com/xeipuuv/gojsonpointer
* https://github.com/xeipuuv/gojsonreference

### Implementation suggestion

We can implement this as a separate package so other people can benefit from it too.

- [ ] :bug: Unit tests
- [ ] :books: Documentation

**Comment by MikeRalphson** [comment]
Idea: if there are existing Go libraries for `$ref` resolution, this may be achieved by 'hiding' the `$ref`s within `schema` objects e.g. by temporarily renaming them (or by detaching and later re-attaching the `schema` objects themselves).

**Comment by fmvilas** [comment]
I was thinking the same but seems there's nothing that resolves $refs in Go :/

**Comment by MikeRalphson** [comment]
Resolving external `$ref`s in Javascript cost me quite a lot in coffee...

**Comment by fmvilas** [comment]
I know, prepare some more coffee for us too 😄

**Comment by drejahl** [comment]
So the requested functionality is actually the below, right?
https://github.com/APIDevTools/swagger-parser/blob/master/docs/swagger-parser.md#resolveapi-options-callback

**Comment by fmvilas** [comment]
Almost! It's this one: https://github.com/APIDevTools/swagger-parser/blob/master/docs/swagger-parser.md#dereferenceapi-options-callback

**Comment by drejahl** [comment]
Ah, ok thanks for clarification.
Let's me think about how this can be done (in Go)....

**Comment by fmvilas** [comment]
Great! Let us know if you need help!

**Comment by drejahl** [comment]
Just to manage expectations - I have no experience in Go (I started looking at it this weekend) so it will take some time ;-)

**Comment by fmvilas** [comment]
No problem! This issue is not blocking anything else in the pipeline, so take your time and make sure you enjoy it! :)

**Comment by xino12** [comment]
There is a working version of this in the parser right now so I'm going to close this issue for now.

Any improvement or addition to this functionality can be created in another issue.

**Comment by fmvilas** [comment]
This is awesome! :tada:
