### ISSUE TITLE
Create Node.js parser wrapper

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/parser#24]
Implement a Node.js wrapper of the Go one, by using the C shared object resulting from the compilation here: https://github.com/asyncapi/parser/blob/master/compile.sh.

There's already some experimental work here: https://github.com/asyncapi/parser-nodejs. It would be nice to continue working there.

It should be fairly straightforward to code but we need to make sure we understand how to compile C for different platforms and architectures.

### References

* https://gist.github.com/steeve/6905542#gistcomment-1988684
* https://github.com/nodejs/node-gyp

**Comment by rmelian** [comment]
I'm assigning this to me if thats okay

**Comment by fmvilas** [comment]
If you're working on it, please move it to "In Progress".
