### ISSUE TITLE
Create AsyncAPI data structures

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/parser#4]
- [x] Info Object
- [x] Servers Array
- [x] Security Object
- [x] Schema Object
- [x] Operation Object
- [x] Message Object
- [x] Security Schemes Object
- [x] Channel Parameters Object
- [x] Tags Object
- [x] External Docs Object
- [x] Channels Object
- [x] Components Object

**Comment by rmelian** [comment]
is there a repo for this already ??

**Comment by fmvilas** [comment]
I'm taking care of the InfoObject for now.

**Comment by MikeRalphson** [comment]
Will the Go code be generated from the JSON Schema or written by hand?

**Comment by fmvilas** [comment]
I'm doing it manually now. Do you know some way to automate it? That would be awesome.

**Comment by fmvilas** [comment]
Looking at this repo: https://github.com/getkin/kin-openapi

**Comment by fmvilas** [comment]
I'm looking at https://github.com/atombender/go-jsonschema and https://github.com/a-h/generate. The last one works but doesn't perform any validation and doesn't support `x-` extensions. The first one is not yet there and can't even deal with `additionalItems`.

**Comment by MikeRalphson** [comment]
I was thinking of simply bootstrapping the boilerplate code using the existing node Codegen and new templates.

**Comment by fmvilas** [comment]
Oh! This is interesting. Want to give it a try yourself?

**Comment by MikeRalphson** [comment]
Yes if it can wait a day or two.

**Comment by fmvilas** [comment]
Oh sure, no rush 😄. I'll keep going with this to learn more about Go. Also, this code could serve you as a template.

**Comment by MikeRalphson** [comment]
Perfect.
