### ISSUE TITLE
Can't refer to a key that has "." in it

### ISSUE THREAD

**Issue by hexdigest** [asyncapi/parser#40]
Hi!

I have a document with the following structure:
```yaml
channels:
  hello.world:
    publish:
      message:
        payload:
          type: object
          required:
            - address
          properties:
            name:
              type: string
            address:
              $ref: "#/channels/hello.world/publish/message/payload/definitions/address"
            status:
              $ref: "#/channels/hello.world/publish/message/payload/definitions/status"

```

"." in the topic is very common for many message brockers but unfortunately references can't be resolved because of this piece of code:

filedereferencer.go:
```go
path := strings.Split(strings.Trim(ref, "#"), "/")
element := m.Get(trimFirstRune(strings.Join(path, ".")))
```

which generates incorrect path to look up for the substituion:
"channels.hello.world.publish.message.payload.definitions.address"

**Comment by fmvilas** [comment]
Thanks for reporting, @hexdigest!

@xino12 can you have a look at this? Thanks!

**Comment by fmvilas** [comment]
This is already fixed. Thanks!
